//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTPKonsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbledit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbledit()
        {
            this.tbleditFiles = new HashSet<tbleditFile>();
        }
    
        public int idedit { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<int> fkperson { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
    
        public virtual tblperson tblperson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbleditFile> tbleditFiles { get; set; }
    }
}
