//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClonestoneMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcard()
        {
            this.tbldeckcards = new HashSet<tbldeckcard>();
        }
    
        public int idcard { get; set; }
        public string cardname { get; set; }
        public byte mana { get; set; }
        public short life { get; set; }
        public short attack { get; set; }
        public string flavor { get; set; }
        public int fktype { get; set; }
        public Nullable<int> fkclass { get; set; }
        public Nullable<int> fkability { get; set; }
        public byte[] pic { get; set; }
    
        public virtual tblability tblability { get; set; }
        public virtual tblclass tblclass { get; set; }
        public virtual tbltype tbltype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbldeckcard> tbldeckcards { get; set; }
    }
}
