//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClonestoneMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldeckcard
    {
        public int iddeckcard { get; set; }
        public int fkdeck { get; set; }
        public int fkcard { get; set; }
    
        public virtual tblcard tblcard { get; set; }
        public virtual tbldeck tbldeck { get; set; }
    }
}
