//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClonestoneMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldeckcard
    {
        public int iddeckcard { get; set; }
        public int fkdeck { get; set; }
        public int fkcard { get; set; }
    
        public virtual tblcard tblcard { get; set; }
        public virtual tbldeck tbldeck { get; set; }
    }
}
