//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClonestoneMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbleditFile
    {
        public int ideditfile { get; set; }
        public int fkedit { get; set; }
        public System.Guid uidfile { get; set; }
        public byte[] editfile { get; set; }
        public string mimetype { get; set; }
    
        public virtual tbledit tbledit { get; set; }
    }
}
