//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClonestoneMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblgame
    {
        public int idgame { get; set; }
        public Nullable<int> fkperson1 { get; set; }
        public Nullable<int> fkperson2 { get; set; }
        public Nullable<byte> win { get; set; }
        public Nullable<System.DateTime> gamestart { get; set; }
        public Nullable<System.DateTime> gameende { get; set; }
    
        public virtual tblperson tblperson { get; set; }
        public virtual tblperson tblperson1 { get; set; }
    }
}
